### PR TITLE
update docs about custom scalyr region

### PR DESCRIPTION
**Pull request by pheanex**
The corresponding code change:
https://github.com/zalando-zmon/zmon-worker/pull/410/files

Do not merge before code in mentioned PR is merged

Please review @vwiessner @anton-ryzhov

### CODE REVIEW

**Comment by pheanex** [comment]
:+1:

**Review by vwiessner — APPROVED** [review]
lgtm

**Comment by vwiessner** [comment]
:+1:

**Comment by pheanex** [comment]
As discussed, won't do

**Pull request closed without merging**
